### PR TITLE
Fix up Travis config

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by bcremer** [comment]
Thanks @GrahamCampbell, fix look good for me. 
@dnoegel lgtm.

**Comment by dnoegel** [comment]
Thanks @GrahamCampbell

**Comment by dnoegel** [comment]
The build still breaks for older php versions. As far as I understand, i could:
- remove those versions
- add the config option "dist: trusty" to the travis.yaml
Any opinions on this? Personally I think supporting unsupported PHP-versions might not be necessary anymore?

**Comment by GrahamCampbell** [comment]
Not broken?

https://travis-ci.org/dnoegel/php-xdg-base-dir/builds/620467387

**Comment by dnoegel** [comment]
Broken

https://travis-ci.org/dnoegel/php-xdg-base-dir/builds/619109711?utm_source=github_status&utm_medium=notification
https://travis-ci.org/dnoegel/php-xdg-base-dir/builds/617464212?utm_source=github_status&utm_medium=notification

**Comment by GrahamCampbell** [comment]
Not broken. The PR is just based off of a branch with a broken travis config. If they rebase on master with the new config, it will work.

**Pull request merged**
